### ISSUE TITLE
How can i chamge this?

### ISSUE THREAD

**Issue by Suddenx-Kemo** [AnirudhRahul/opsu-Android#30]
![received_2721264301244607](https://user-images.githubusercontent.com/61066347/74567358-90c6af80-4fb0-11ea-9416-c57d8e7b21e2.jpeg)
How can i chamge this? 
I found the entire folder of game (using apk editor pro) still don't know how to change that. 
please tell me X3

**Comment by kolejker** [comment]
you cant
its not a texture

**Comment by Suddenx-Kemo** [comment]
> you cant
> its not a texture

Thanks dude
I'm just playing this game and see your comment xD
