### ISSUE TITLE
New App Update soon?

### ISSUE THREAD

**Issue by kairusds** [AnirudhRahul/opsu-Android#33]
It's almost a year and I can't wait to update the app for what seems like an eternity but before that there's a lot of bugs I want to report like how ads always show in-game if they don't show up after you finish a map, how the screen gets spammed with error messages when you show the Top Global rankings of a map when your internet is slow or turned off

**Comment by Sulu1415** [comment]
UPDATE THE APP
PLEASE
FOR GOD'S SAKE
THIS IS THE MOST SOLID OSU PLAYER FOR ANDROID
**PLEASE**
