### ISSUE TITLE
FPS Drop with sliders

### ISSUE THREAD

**Issue by kairusds** [AnirudhRahul/opsu-Android#37]
I just noticed this while playing but hitting sliders for me drops the fps from 59-56 and it keeps stuttering

**Comment by KornienkoDev** [comment]
I have fps drops also. On Android 10 unplayable atm. They occur on every hitsound been played. If disable hitsounds - no more fps drops.

**Comment by kairusds** [comment]
> I have fps drops also. On Android 10 unplayable atm. They occur on every hitsound been played. If disable hitsounds - no more fps drops.

did you try changing the sound effect files from the skin to mp3?

**Comment by KornienkoDev** [comment]
> > I have fps drops also. On Android 10 unplayable atm. They occur on every hitsound been played. If disable hitsounds - no more fps drops.
> 
> did you try changing the sound effect files from the skin to mp3?

just tried to convert hitsounds to mp3 and place them into skin - didn't helped at all.

**Comment by kairusds** [comment]
> > > I have fps drops also. On Android 10 unplayable atm. They occur on every hitsound been played. If disable hitsounds - no more fps drops.
> > 
> > 
> > did you try changing the sound effect files from the skin to mp3?
> 
> just tried to convert hitsounds to mp3 and place them into skin - didn't helped at all.

oof then idk how to fix it

**Comment by KornienkoDev** [comment]
> > > > I have fps drops also. On Android 10 unplayable atm. They occur on every hitsound been played. If disable hitsounds - no more fps drops.
> > > 
> > > 
> > > did you try changing the sound effect files from the skin to mp3?
> > 
> > 
> > just tried to convert hitsounds to mp3 and place them into skin - didn't helped at all.
> 
> oof then idk how to fix it

only devs know. which are abandoned this project
