### ISSUE TITLE
no options glitch

### ISSUE THREAD

**Issue by brahbersan** [AnirudhRahul/opsu-Android#50]
![Screenshot 2021-08-14 9 52 05 PM](https://user-images.githubusercontent.com/88945560/129457503-f875ae61-bdbd-44ad-a1e2-f3d9e76288ff.png)
i play on a chromebook and got a skin that wont show options. how do i get it back??

**Comment by MFDaus47** [comment]
I've once had the same problem. You need to remove the selection-mods(or whatever).PNG that looks blank. It looks like this 
![IMG_20210815_091912.jpg](https://user-images.githubusercontent.com/79355837/129463965-9655ea55-80c9-4f85-ace0-5d8d9d4f2bf6.jpg)

However this wont change the mods, options icon or whatever. You can go to osuskinner.com to change your own. Try to figure it out but you can't still reply to me to ask some questions. 
Reminder that if you want to change only little things to the skins, do not copy paste the skin.ini too. It's hard to understand so ask me when you need to.

**Comment by brahbersan** [comment]
my only problem is finding these .png's on my chromebook.
do you know where i can find them? i tried looking through files but it showed only 2 skins (none of which are the one im dealing with)

**Comment by MFDaus47** [comment]
> my only problem is finding these .png's on my chromebook.
> do you know where i can find them? i tried looking through files but it showed only 2 skins (none of which are the one im dealing with)

That's weird how can you use a skin that has no folder. You sure 2 of those skin folder not the one you're having problem right now?

**Comment by MFDaus47** [comment]
I don't have a Chromebook nor PC. Do you have opsu.cfg in the opsu folder? If you do open that as a text (in Android WPS office works). Then read a few lines until you Skin = 'skin name' you can see what skin are you actually dealing with. You can change the 'skin name' to Default for temporary fix, then change to your working skin like usual. It should look like Skin = Default

You can still use the 'problematic' skin after you modified the problem part(the .PNG i said at first)

**Comment by brahbersan** [comment]
ah it worked, i found the opsu folder and deleted the skin, i didn't like it anyway lol. tyvm for the help.
