### ISSUE TITLE
GNU GPL V3 Licence

### ISSUE THREAD

**Issue by 12458** [AnirudhRahul/opsu-Android#9]
Please include a copy of the GNU GPL V3 Licence to conform to the requirement that a License and copyright notice must be included with the software.
[https://choosealicense.com/licenses/gpl-3.0](https://choosealicense.com/licenses/gpl-3.0)

**Comment by AnirudhRahul** [comment]
It is in the readme already is there a different place that I should put it?

**Comment by 12458** [comment]
There should be a separate file which contains the full text of the licence.
